spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      server:
        webflux:
          # Service discovery through Eureka
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true

          # Routes
          routes:
            - id: room-service
              uri: lb://room-service
              predicates:
                - Path=/room-service/**
              filters:
                - RemoveRequestHeader=Cookie
            - id: chat-service
              uri: lb://chat-service
              predicates:
                - Path=/chat-service/**
              filters:
                - RemoveRequestHeader=Cookie

server:
  port: 8765

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    registerWithEureka: true
    fetchRegistry: true
  instance:
    prefer-ip-address: true
